// ADR index extraction (DIO-180): number + title + first sentence +
// supersession stamps per ADR, mechanically extracted so the index is a
// generated artifact — rot-proof, never hand-edited, CI-checked like the
// other renderings. Extracted to lib so it is unit-testable (render.mjs
// runs render() on import, same reason as frontmatter.mjs).

// Stamp grammar (both shapes in the corpus): a line whose bold prefix is
// "Superseded [in part] by ADR-NNNN" or "... by [ADR-NNNN](...)", either as
// a top-of-file blockquote or an inline paragraph (ADR-0010's style).
const STAMP_RE = /\*\*Superseded( in part)? by \[?ADR-(\d{4})/g;

export function supersessionStamps(body) {
  const out = [];
  for (const m of body.matchAll(STAMP_RE)) {
    out.push({ partial: Boolean(m[1]), by: m[2] });
  }
  return out;
}

// First sentence of the first prose paragraph — skipping the # title,
// blockquote stamp lines, and blank lines. ADR bodies are hard-wrapped at
// ~80 cols, so the paragraph's lines are joined before sentence-splitting
// (line-by-line extraction shipped mid-clause fragments — review finding,
// PR #203). Capped so a runaway first sentence can't bloat the index (same
// instinct as the agent index's brief()).
export function firstSentence(body) {
  const paragraph = [];
  for (const rawLine of body.split("\n")) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#") || line.startsWith(">")) {
      if (paragraph.length) break; // paragraph ended
      continue; // still skipping preamble
    }
    paragraph.push(line);
  }
  if (!paragraph.length) return "";
  let s = paragraph.join(" ").split(/(?<=\.)\s/)[0].trim();
  if (s.length > 200) s = s.slice(0, 199).trimEnd() + "…";
  return s;
}

// An ADR body's own links to sibling ADRs are relative to the ADR dir — e.g.
// "[ADR-0043](0043-foo.md)" — but the index they get embedded into lives one
// level up at zdd/adr-index.md, where that href resolves to zdd/0043-foo.md
// and 404s. Supersession sentences are the common case (they open with a link
// to the ADR they supersede), so most stamped ADRs carried a broken link into
// the index. Rebase bare NNNN-*.md targets onto adr/; leave anything already
// qualified, absolute, or anchored alone. Found by the DIO-226 review lane.
const ADR_HREF_RE = /\]\((\d{4}-[^)/#]+\.md)/g;

export function rebaseAdrLinks(text) {
  return text.replace(ADR_HREF_RE, "](adr/$1");
}

// One line per ADR, numerically sorted. Hrefs are relative to zdd/ (the
// index lives at zdd/adr-index.md) so they resolve on GitHub, matching the
// agent index's convention — including the links carried inside an extracted
// first sentence, which is what rebaseAdrLinks above is for.
export function buildAdrIndex(adrs) {
  const lines = [];
  lines.push("# ADR index");
  lines.push("");
  lines.push(
    "One line per ADR: number — title — first sentence, plus supersession stamps.",
    "Generated by `zdd-engine render` from the ADR corpus — do not edit.",
    "Read this whole at orientation; drill into full ADR bodies only when cited",
    "(by the task, the spec, the glossary, or the agent index) — and declare the",
    "selection.",
  );
  lines.push("");
  const sorted = [...adrs].sort((a, b) => (a.num < b.num ? -1 : 1));
  for (const adr of sorted) {
    const sentence = rebaseAdrLinks(firstSentence(adr.body));
    const stamps = supersessionStamps(adr.body);
    let line = `- [ADR-${adr.num}](adr/${adr.file}) — ${adr.title}`;
    if (sentence) line += ` — ${sentence}`;
    const partial = stamps.filter((s) => s.partial).map((s) => `ADR-${s.by}`);
    const full = stamps.filter((s) => !s.partial).map((s) => `ADR-${s.by}`);
    if (full.length) line += ` _(superseded by ${full.join(", ")})_`;
    if (partial.length) line += ` _(superseded in part by ${partial.join(", ")})_`;
    lines.push(line);
  }
  lines.push("");
  return lines.join("\n");
}
