// Blessing index (CAS-96): one line per blessing in the semantic map, so a
// session choosing patterns reads every trigger question at once and opens
// only the blessings that match its work. Generated like the ADR index —
// mechanically extracted, never hand-edited, checked by `render --check` —
// and in lib so it is unit-testable (render.mjs runs render() on import).
//
// Grouped by slice, app-level slices (Application / Package concepts) first:
// their blessings are cross-cutting, and every one is read in full for an
// app the work touches. Each line is the trigger question and the reason: the
// ADRs it cites, else its "because …" clause. A blessing that opens with no
// question is still listed, flagged, so nothing in the map is invisible here
// even before lint fails it. Measured on a real map: ~95 tokens per blessing
// in full against ~15 per line here, which is what keeps the index loadable
// whole at a thousand blessings.

import { extractBlessings, blessingShape } from "./map-links.mjs";

const APP_TYPES = new Set(["Application", "Package"]);
const OPENING_MAX = 80;

const printable = (t) => t.replace(/[\x00-\x1f\x7f]/g, "?");

// `concepts`: map concepts as render builds them ({ id, type, title, body }).
// `adrHref(num)`: the index-relative href of an ADR, or null if it does not
// exist (the citation is then printed bare; lint reports it). Returns the
// index text and the number of blessings in it.
export function buildBlessingIndex(concepts, adrHref) {
  const bySlice = [];
  for (const c of concepts) {
    const blessings = extractBlessings(c.body);
    if (blessings.length) bySlice.push({ c, blessings, app: APP_TYPES.has(c.type) });
  }
  const order = (a, b) => (a.c.title < b.c.title ? -1 : a.c.title > b.c.title ? 1 : a.c.id < b.c.id ? -1 : a.c.id > b.c.id ? 1 : 0);
  const apps = bySlice.filter((s) => s.app).sort(order);
  const slices = bySlice.filter((s) => !s.app).sort(order);
  const total = bySlice.reduce((n, s) => n + s.blessings.length, 0);

  const lines = [];
  lines.push("# Blessing index", "");
  lines.push(
    "One line per blessing in the semantic map: its trigger question — its reason.",
    "Generated by `zdd-engine render` from the map's `# Blessings` sections — do not edit.",
    "Read this whole when choosing patterns, and open a blessing in full (in its",
    "slice) only when its question matches the work. App-level blessings come",
    "first: for an app the work touches, read every one of them in full.",
    "",
  );
  if (!total) {
    lines.push("No blessings yet. A blessing names the exemplar to copy and the pattern to", "refuse, under a `# Blessings` heading in a slice; `update` mints them.", "");
    return { text: lines.join("\n"), count: 0 };
  }
  const section = (title, list) => {
    if (!list.length) return;
    lines.push(`## ${title}`, "");
    for (const { c, blessings } of list) {
      lines.push(`### [${printable(c.title)}](${c.id}.md)`, "");
      for (const b of blessings) lines.push(`- ${line(b, adrHref)}`);
      lines.push("");
    }
  };
  section("App-level", apps);
  section("Slices", slices);
  return { text: lines.join("\n"), count: total };
}

function line(blessing, adrHref) {
  const shape = blessingShape(blessing.text);
  const head = shape.question
    ? printable(shape.question)
    : `_(no trigger question)_ ${printable(shape.visible.length > OPENING_MAX ? shape.visible.slice(0, OPENING_MAX - 1).trimEnd() + "…" : shape.visible)}`;
  let reason;
  if (blessing.adrs.length) {
    reason = blessing.adrs.map((n) => (adrHref(n) ? `[ADR-${n}](${adrHref(n)})` : `ADR-${n}`)).join(", ");
  } else if (shape.because) {
    reason = printable(shape.because);
  } else {
    reason = "_no reason given_";
  }
  return `${head} — ${reason}`;
}
