#!/usr/bin/env node
// ZDD generated-artifact fence — a PreToolUse hook. The five generated
// artifacts (codebase metadata, graph, agent index, ADR index, human index)
// are regenerated by `update`, never hand-edited; CI catches a hand edit
// eventually, but by then the agent has spent a turn on it and the diff is
// noise. This hook refuses the write up front, with a reason that names the
// ritual, so the agent regenerates instead.
//
// Opt-in per repo: it does nothing unless the adopter's VALID zdd/config.json
// says `"hooks": { "fence": true }` (bootstrap writes that on a "yes"). Paths
// come from the same config (`paths.*`), validated repo-relative, so a repo
// that moved its artifacts is fenced where they actually are. Never fails a
// session: no config, malformed config, unreadable stdin — exit 0, silently.
// Blocking is the JSON PreToolUse deny reply on stdout (exit 0) — the shape
// both hosts honour; exit 2 fails open in Codex (decision 0007).
//
// What it inspects: direct edit tools (file_path), Codex's apply_patch (the
// file lines of the patch), and shell commands. The shell half is BEST-EFFORT
// by nature — it recognises redirection, in-place edits, copies/moves/removes
// and script-language one-liners naming a generated path, resolved against the
// command's cwd; a sufficiently creative command can still get past it. The
// merge gate (CI) or the pre-push hook is the guarantee; the fence saves the
// turn. Documented in docs/decisions/0003.

import { readFileSync, realpathSync, existsSync } from "node:fs";
import { resolve, isAbsolute, dirname, relative, join } from "node:path";
import { adopterRoot, readConfig, artifactPaths, resolveInside, samePath, isUnder } from "./lib/repo.mjs";

const EDIT_TOOLS = new Set(["Write", "Edit", "MultiEdit", "NotebookEdit", "write_file", "edit_file"]);
const SHELL_TOOLS = new Set(["Bash", "PowerShell", "Shell", "shell", "shell_command", "exec_command", "local_shell"]);
const PATCH_TOOLS = new Set(["apply_patch"]);

// Write-shaped shell (case-insensitive): redirection anywhere, in-place edits,
// copies/moves/removes/links, git working-tree writes, PowerShell writers,
// and script-language one-liners (which can write anything).
const WRITE_SHAPED =
  /(>|(^|[\s;&|(])(tee|sed\s+(-[a-z]*i|--in-place)|cp|mv|rm|del|erase|rmdir|truncate|dd|install|ln|touch|git\s+(checkout|restore|clean|rm|mv)|set-content|out-file|add-content|clear-content|remove-item|move-item|copy-item|new-item|rename-item|python3?|node|perl|ruby|php)(\s|$))/i;
// Commands whose LAST operand is the destination; other operands are sources.
const LAST_OPERAND_IS_TARGET = /^(cp|mv|copy-item|move-item|install|ln)$/i;

function readStdin() {
  try {
    return readFileSync(0, "utf8");
  } catch {
    return "";
  }
}

// Quote-aware tokens: "a b", 'a b', or bare runs. Leading redirection glued
// to a path (`>zdd/graph.json`) is split off.
function tokens(command) {
  const out = [];
  const re = /"([^"]*)"|'([^']*)'|(\S+)/g;
  let m;
  while ((m = re.exec(command))) {
    let t = m[1] ?? m[2] ?? m[3];
    t = t.replace(/^[><]+|^[0-9]>+/, "").replace(/^["']|["']$/g, "");
    if (t) out.push(t);
  }
  return out;
}

// The real path of a target that may not exist yet: realpath of the nearest
// existing ancestor plus the remaining segments. A UNC or device path
// (`\\server\share`, `\\.\`, `\\?\`) is compared as text and never touched —
// probing it is an SMB or device round-trip with the session's credentials
// (CR-052). An ordinary local path outside the checkout IS probed, because an
// alias link out there can point back at an artifact (CR-055); the command
// about to run would touch that path anyway.
const REMOTE_OR_DEVICE = /^(\\\\|\/\/)/;
const driveOf = (p) => (/^[a-zA-Z]:/.test(p) ? p[0].toLowerCase() : "");
function canonical(abs, root) {
  if (REMOTE_OR_DEVICE.test(abs)) return abs;
  // A different drive letter may be a mapped network share (CR-057): compare
  // as text. An alias on the checkout's own drive is still followed (CR-055).
  if (root && driveOf(abs) !== driveOf(root)) return abs;
  let probe = abs;
  const rest = [];
  while (!existsSync(probe)) {
    const parent = dirname(probe);
    if (parent === probe) return abs;
    rest.unshift(relative(parent, probe));
    probe = parent;
  }
  try {
    return join(realpathSync(probe), ...rest);
  } catch {
    return abs;
  }
}

function patchTargets(text) {
  const out = [];
  const re = /^\*\*\* (?:Add|Update|Delete) File: (.+)$|^\*\*\* Move to: (.+)$/gm;
  let m;
  while ((m = re.exec(text))) out.push((m[1] ?? m[2]).trim());
  return out;
}

function main() {
  let input;
  try {
    input = JSON.parse(readStdin() || "{}");
  } catch {
    return 0;
  }
  const cwdIn = typeof input.cwd === "string" ? input.cwd : undefined;
  const root = adopterRoot({ cwd: cwdIn });
  const { state, config } = readConfig(root);
  if (state !== "valid" || config.hooks?.fence !== true) return 0;

  // Lenient: a bad `paths.*` value falls back to its default on its own; one
  // typo never unfences the rest (CR-070).
  const paths = artifactPaths(config, { lenient: true });
  // Each generated path proven inside the checkout with no symlinked segment
  // (CR-004). One that fails — a symlinked artifact — is dropped on its own;
  // the others stay fenced (CR-051).
  const generated = [];
  for (const g of [
    { rel: paths.metadataDir, kind: "dir" },
    { rel: paths.graph, kind: "file" },
    { rel: paths.agentIndex, kind: "file" },
    { rel: paths.adrIndex, kind: "file" },
    { rel: paths.humanIndex, kind: "file" },
  ]) {
    try {
      generated.push({ ...g, abs: canonical(resolveInside(root, g.rel, g.rel)) });
    } catch {
      /* not a path the fence can vouch for */
    }
  }
  // Shell-relative paths resolve against the command's cwd when it is inside
  // the checkout (CR-023); anything else resolves against the root.
  const cwd = cwdIn && (samePath(cwdIn, root) || isUnder(cwdIn, root)) ? resolve(cwdIn) : root;
  const hit = (candidate, base) => {
    // Compared by REAL path, so an alias link to the artifact or its parent
    // still matches (CR-004).
    const abs = canonical(isAbsolute(candidate) ? resolve(candidate) : resolve(base, candidate), root);
    for (const g of generated) {
      if (samePath(abs, g.abs) || (g.kind === "dir" && isUnder(abs, g.abs))) return g.rel;
    }
    return null;
  };

  const tool = input.tool_name;
  const args = input.tool_input ?? {};
  let target = null;
  if (EDIT_TOOLS.has(tool) && typeof args.file_path === "string") {
    target = hit(args.file_path, cwd);
  } else if (PATCH_TOOLS.has(tool) || typeof args.patch === "string" || (typeof args.command === "string" && /^\*\*\* Begin Patch/m.test(args.command))) {
    const text = typeof args.patch === "string" ? args.patch : typeof args.command === "string" ? args.command : typeof args.input === "string" ? args.input : "";
    for (const p of patchTargets(text)) if ((target = hit(p, cwd))) break;
  } else if (SHELL_TOOLS.has(tool) && typeof args.command === "string" && WRITE_SHAPED.test(args.command)) {
    // Split on command separators so each simple command's operands are
    // judged on their own; for copy-like verbs only the last operand is a
    // destination (CR-019).
    for (const simple of args.command.split(/\|\||&&|;|\||\n/)) {
      const toks = tokens(simple);
      if (!toks.length) continue;
      const verb = toks[0].replace(/^.*[\\/]/, "");
      const operands = toks.slice(1).filter((t) => !t.startsWith("-"));
      // Path-shaped runs anywhere in the command (`node -e "...('zdd/graph.json')"`)
      // are candidates too — a script can write anything it names.
      const literals = [...simple.matchAll(/[\w.:-]*[\\/][\w.\\/:-]*/g)].map((m) => m[0]);
      const candidates = LAST_OPERAND_IS_TARGET.test(verb) && operands.length > 1 ? operands.slice(-1) : /^(cat|less|head|tail|grep|diff|type|get-content)$/i.test(verb) && !/>/.test(simple) ? [] : operands.concat(toks[0], literals);
      for (const c of candidates) if ((target = hit(c, cwd))) break;
      if (target) break;
    }
  }
  if (!target) return 0;

  const reason =
    `ZDD fence: ${target} is a generated artifact — never hand-edit it. ` +
    `Run the ZDD update ritual ("update ZDD" / the \`update\` skill) to regenerate it ` +
    `(zdd-engine derive + render). To lift the fence for this repo set "hooks": { "fence": false } in zdd/config.json.`;
  // The block is the JSON PreToolUse deny reply on stdout with exit 0 — the
  // shape both hosts document AND honour (decision 0007). Exit 2 + stderr was
  // observed to fail open in Codex 0.145.0 (hook "Failed", edit applied). The
  // reason is mirrored on stderr for the hosts' hook logs only.
  process.stdout.write(JSON.stringify({ hookSpecificOutput: { hookEventName: "PreToolUse", permissionDecision: "deny", permissionDecisionReason: reason } }) + "\n");
  process.stderr.write(reason + "\n");
  return 0;
}

let code = 0;
try {
  code = main();
} catch {
  code = 0;
}
// exitCode, not exit(): let stdout/stderr drain so the reply reaches the host (CR-039).
process.exitCode = code;
