#!/usr/bin/env node
// ZDD generated-artifact fence — a PreToolUse hook. The five generated
// artifacts (codebase metadata, graph, agent index, ADR index, human index)
// are regenerated by `update`, never hand-edited; CI catches a hand edit
// eventually, but by then the agent has spent a turn on it and the diff is
// noise. This hook refuses the write up front, with a reason that names the
// ritual, so the agent regenerates instead.
//
// Opt-in per repo: it does nothing unless the adopter's VALID zdd/config.json
// says `"hooks": { "fence": true }` (bootstrap writes that on a "yes"). Paths
// come from the same config (`paths.*`), validated repo-relative, so a repo
// that moved its artifacts is fenced where they actually are. Never fails a
// session: no config, malformed config, unreadable stdin — exit 0, silently.
// Blocking is the JSON PreToolUse deny reply on stdout (exit 0) — the shape
// both hosts honour; exit 2 fails open in Codex (decision 0007).
//
// What it inspects: direct edit tools (file_path), Codex's apply_patch (the
// file lines of the patch), and shell commands. The shell half is BEST-EFFORT
// by nature — it recognises redirection, in-place edits, copies/moves/removes
// and script-language one-liners naming a generated path, resolved against the
// command's cwd; a sufficiently creative command can still get past it. The
// merge gate (CI) or the pre-push hook is the guarantee; the fence saves the
// turn. Documented in docs/decisions/0003.

import { readFileSync, realpathSync, existsSync } from "node:fs";
import { resolve, isAbsolute, dirname, relative, join } from "node:path";
import { adopterRoot, readConfig, artifactPaths, resolveInside, samePath, isUnder } from "./lib/repo.mjs";

const EDIT_TOOLS = new Set(["Write", "Edit", "MultiEdit", "NotebookEdit", "write_file", "edit_file"]);
const SHELL_TOOLS = new Set(["Bash", "PowerShell", "Shell", "shell", "shell_command", "exec_command", "local_shell"]);
const PATCH_TOOLS = new Set(["apply_patch"]);

// Write-shaped shell (case-insensitive): redirection anywhere, in-place edits,
// copies/moves/removes/links, git working-tree writes, PowerShell writers,
// and script-language one-liners (which can write anything).
const WRITE_SHAPED =
  /(>|(^|[\s;&|(])(tee|sed\s+(-[a-z]*i|--in-place)|cp|mv|rm|del|erase|rmdir|truncate|dd|install|ln|touch|git\s+(checkout|restore|clean|rm|mv)|set-content|out-file|add-content|clear-content|remove-item|move-item|copy-item|new-item|rename-item|python3?|node|perl|ruby|php)(\s|$))/i;
// Commands whose LAST operand is the destination and the others are read-only
// sources. A move is NOT one of them: `mv zdd/graph.json elsewhere` removes
// the artifact, so every operand of mv/move-item/rename-item/git mv is a
// candidate (CR-072).
const LAST_OPERAND_IS_TARGET = /^(cp|copy-item|install|ln)$/i;
// Verbs that take a whole tree with them: an ancestor of a generated path is
// as good as the path (CR-071). `git clean` / `git rm` are handled by sub-verb.
const DESTRUCTIVE = /^(rm|rmdir|rd|del|erase|unlink|remove-item|ri)$/i;

function readStdin() {
  try {
    return readFileSync(0, "utf8");
  } catch {
    return "";
  }
}

// Quote-aware tokens: "a b", 'a b', or bare runs. Leading redirection glued
// to a path (`>zdd/graph.json`) is split off.
function tokens(command) {
  const out = [];
  const re = /"([^"]*)"|'([^']*)'|(\S+)/g;
  let m;
  while ((m = re.exec(command))) {
    let t = m[1] ?? m[2] ?? m[3];
    t = t.replace(/^[><]+|^[0-9]>+/, "").replace(/^["']|["']$/g, "");
    if (t) out.push(t);
  }
  return out;
}

// The real path of a target that may not exist yet: realpath of the nearest
// existing ancestor plus the remaining segments. A UNC or device path
// (`\\server\share`, `\\.\`, `\\?\`) is compared as text and never touched —
// probing it is an SMB or device round-trip with the session's credentials
// (CR-052). An ordinary local path outside the checkout IS probed, because an
// alias link out there can point back at an artifact (CR-055); the command
// about to run would touch that path anyway.
const REMOTE_OR_DEVICE = /^(\\\\|\/\/)/;
const driveOf = (p) => (/^[a-zA-Z]:/.test(p) ? p[0].toLowerCase() : "");
function canonical(abs, root) {
  if (REMOTE_OR_DEVICE.test(abs)) return abs;
  // A different drive letter may be a mapped network share (CR-057): compare
  // as text. An alias on the checkout's own drive is still followed (CR-055).
  if (root && driveOf(abs) !== driveOf(root)) return abs;
  let probe = abs;
  const rest = [];
  while (!existsSync(probe)) {
    const parent = dirname(probe);
    if (parent === probe) return abs;
    rest.unshift(relative(parent, probe));
    probe = parent;
  }
  try {
    return join(realpathSync(probe), ...rest);
  } catch {
    return abs;
  }
}

function patchTargets(text) {
  const out = [];
  const re = /^\*\*\* (?:Add|Update|Delete) File: (.+)$|^\*\*\* Move to: (.+)$/gm;
  let m;
  while ((m = re.exec(text))) out.push((m[1] ?? m[2]).trim());
  return out;
}

function patchTarget(text, cwd, hit) {
  for (const p of patchTargets(text)) {
    const t = hit(p, cwd);
    if (t) return t;
  }
  return null;
}

// The shell half. Split on command separators so each simple command's
// operands are judged on their own; for copy-like verbs only the last operand
// is a destination (CR-019).
function shellTarget(command, cwd, hit) {
  if (!command || !WRITE_SHAPED.test(command)) return null;
  for (const simple of command.split(/\|\||&&|;|\||\n/)) {
    const toks = tokens(simple);
    if (!toks.length) continue;
    const verb = toks[0].replace(/^.*[\\/]/, "");
    const operands = toks.slice(1).filter((t) => !t.startsWith("-"));
    // Path-shaped runs anywhere in the command (`node -e "...('zdd/graph.json')"`)
    // are candidates too — a script can write anything it names.
    const literals = [...simple.matchAll(/[\w.:-]*[\\/][\w.\\/:-]*/g)].map((m) => m[0]);
    // `-t DIR` / `--target-directory[= ]DIR` names the destination up front
    // (CR-071); it is a candidate whatever the operand order.
    const targetDirs = [];
    toks.forEach((t, i) => {
      const eq = /^--target-directory=(.+)$/.exec(t);
      if (eq) targetDirs.push(eq[1]);
      else if ((t === "-t" || t === "--target-directory") && toks[i + 1]) targetDirs.push(toks[i + 1]);
    });
    const copyLike = LAST_OPERAND_IS_TARGET.test(verb);
    const candidates =
      copyLike && targetDirs.length
        ? targetDirs // every operand is a source
        : copyLike && operands.length > 1
          ? operands.slice(-1)
          : /^(cat|less|head|tail|grep|diff|type|get-content)$/i.test(verb) && !/>/.test(simple)
            ? []
            : operands.concat(toks[0], literals, targetDirs);
    // A destructive verb over an ANCESTOR of a generated path takes the
    // artifact with it (`rm -rf zdd`), so for those verbs an ancestor is a hit
    // too (CR-071). Globs and variables stay opaque — decision 0003's ceiling.
    const destructive = DESTRUCTIVE.test(verb) || (/^git$/i.test(verb) && /^(clean|rm)$/i.test(toks[1] ?? ""));
    for (const c of candidates) {
      const t = hit(c, cwd, { ancestor: destructive });
      if (t) return t;
    }
  }
  return null;
}

function main() {
  let input;
  try {
    input = JSON.parse(readStdin() || "{}");
  } catch {
    return 0;
  }
  const cwdIn = typeof input.cwd === "string" ? input.cwd : undefined;
  const root = adopterRoot({ cwd: cwdIn });
  const { state, config } = readConfig(root);
  if (state !== "valid" || config.hooks?.fence !== true) return 0;

  // Lenient: a bad `paths.*` value falls back to its default on its own; one
  // typo never unfences the rest (CR-070).
  const paths = artifactPaths(config, { lenient: true });
  // Each generated path proven inside the checkout with no symlinked segment
  // (CR-004). One that fails — a symlinked artifact — is dropped on its own;
  // the others stay fenced (CR-051).
  const generated = [];
  for (const g of [
    { rel: paths.metadataDir, kind: "dir" },
    { rel: paths.graph, kind: "file" },
    { rel: paths.agentIndex, kind: "file" },
    { rel: paths.adrIndex, kind: "file" },
    { rel: paths.humanIndex, kind: "file" },
  ]) {
    try {
      generated.push({ ...g, abs: canonical(resolveInside(root, g.rel, g.rel)) });
    } catch {
      /* not a path the fence can vouch for */
    }
  }
  // Shell-relative paths resolve against the command's own directory when it
  // is inside the checkout (CR-023); anything else resolves against the root.
  // The command's directory is the tool's own field first — Codex's
  // `shell_command` carries `workdir`, some tools `cwd` — and the session cwd
  // only as the fallback (CR-076).
  const toolInput = input.tool_input && typeof input.tool_input === "object" ? input.tool_input : {};
  const cmdDir = [toolInput.workdir, toolInput.cwd, cwdIn].find((v) => typeof v === "string" && v.length);
  const cwd = cmdDir && (samePath(cmdDir, root) || isUnder(cmdDir, root)) ? resolve(cmdDir) : root;
  const hit = (candidate, base, { ancestor = false } = {}) => {
    // Compared by REAL path, so an alias link to the artifact or its parent
    // still matches (CR-004).
    const abs = canonical(isAbsolute(candidate) ? resolve(candidate) : resolve(base, candidate), root);
    for (const g of generated) {
      if (samePath(abs, g.abs) || (g.kind === "dir" && isUnder(abs, g.abs))) return g.rel;
      if (ancestor && isUnder(g.abs, abs)) return g.rel;
    }
    return null;
  };

  const tool = input.tool_name;
  const args = input.tool_input && typeof input.tool_input === "object" ? input.tool_input : {};
  const str = (v) => (typeof v === "string" ? v : "");
  // Dispatch on the TOOL NAME, never on which fields happen to be present: a
  // shell payload carrying a stray `patch` string must still have its
  // `command` inspected (CR-073). Extra fields are inspected additionally.
  let target = null;
  if (EDIT_TOOLS.has(tool)) {
    if (str(args.file_path)) target = hit(args.file_path, cwd);
  } else if (PATCH_TOOLS.has(tool)) {
    target = patchTarget(str(args.patch) || str(args.input) || str(args.command), cwd, hit);
  } else if (SHELL_TOOLS.has(tool)) {
    const command = str(args.command);
    target = shellTarget(command, cwd, hit);
    if (!target && /^\*\*\* Begin Patch/m.test(command)) target = patchTarget(command, cwd, hit);
    if (!target && str(args.patch)) target = patchTarget(args.patch, cwd, hit);
  } else if (str(args.patch)) {
    target = patchTarget(args.patch, cwd, hit);
  }
  if (!target) return 0;

  const reason =
    `ZDD fence: ${target} is a generated artifact — never hand-edit it. ` +
    `Run the ZDD update ritual ("update ZDD" / the \`update\` skill) to regenerate it ` +
    `(zdd-engine derive + render). To lift the fence for this repo set "hooks": { "fence": false } in zdd/config.json.`;
  // The block is the JSON PreToolUse deny reply on stdout with exit 0 — the
  // shape both hosts document AND honour (decision 0007). Exit 2 + stderr was
  // observed to fail open in Codex 0.145.0 (hook "Failed", edit applied). The
  // reason is mirrored on stderr for the hosts' hook logs only.
  process.stdout.write(JSON.stringify({ hookSpecificOutput: { hookEventName: "PreToolUse", permissionDecision: "deny", permissionDecisionReason: reason } }) + "\n");
  process.stderr.write(reason + "\n");
  return 0;
}

let code = 0;
try {
  code = main();
} catch {
  code = 0;
}
// exitCode, not exit(): let stdout/stderr drain so the reply reaches the host (CR-039).
process.exitCode = code;
