#!/usr/bin/env node
// ZDD generated-artifact fence — a PreToolUse hook. The four generated
// artifacts (codebase metadata, graph, agent index, ADR index, human index)
// are regenerated by `update`, never hand-edited; CI catches a hand edit
// eventually, but by then the agent has spent a turn on it and the diff is
// noise. This hook refuses the write up front, with a reason that names the
// ritual, so the agent regenerates instead.
//
// Opt-in per repo: it does nothing unless the adopter's zdd/config.json says
// `"hooks": { "fence": true }` (bootstrap writes that on a "yes"). Paths come
// from the same config (`paths.*`), so a repo that moved its artifacts is
// fenced where they actually are. Never fails a session: no config, malformed
// config, unreadable stdin — exit 0, silently. Blocking is exit 2 + stderr,
// the one signal every host honours.

import { readFileSync } from "node:fs";
import { resolve, relative, isAbsolute } from "node:path";
import { adopterRoot, loadConfig, artifactPaths, posixify } from "./lib/repo.mjs";

const WRITE_TOOLS = new Set(["Write", "Edit", "MultiEdit", "NotebookEdit"]);
const SHELL_TOOLS = new Set(["Bash", "PowerShell", "Shell"]);
// Write-shaped shell: redirection, in-place edits, copies/moves/removes.
const WRITE_SHAPED = /(^|[\s;&|])(>>?|tee|sed\s+(-[a-zA-Z]*i|--in-place)|cp|mv|rm|truncate|Set-Content|Out-File|Add-Content|Remove-Item|Move-Item|Copy-Item)(\s|$)/;

function readStdin() {
  try {
    return readFileSync(0, "utf8");
  } catch {
    return "";
  }
}

function main() {
  let input;
  try {
    input = JSON.parse(readStdin() || "{}");
  } catch {
    return 0;
  }
  const root = adopterRoot({ root: input.cwd && !process.env.CLAUDE_PROJECT_DIR ? input.cwd : undefined });
  const config = loadConfig(root);
  if (!config || config.hooks?.fence !== true) return 0;

  const paths = artifactPaths(config);
  const generated = {
    [paths.metadataDir]: "dir",
    [paths.graph]: "file",
    [paths.agentIndex]: "file",
    [paths.adrIndex]: "file",
    [paths.humanIndex]: "file",
  };
  const hit = (candidate) => {
    const abs = isAbsolute(candidate) ? candidate : resolve(root, candidate);
    const rel = posixify(relative(root, abs));
    if (rel.startsWith("../") || rel === "..") return null;
    for (const [p, kind] of Object.entries(generated)) {
      const norm = posixify(p).replace(/\/+$/, "");
      if (rel === norm || (kind === "dir" && rel.startsWith(norm + "/"))) return norm;
    }
    return null;
  };

  const tool = input.tool_name;
  const args = input.tool_input ?? {};
  let target = null;
  if (WRITE_TOOLS.has(tool) && typeof args.file_path === "string") {
    target = hit(args.file_path);
  } else if (SHELL_TOOLS.has(tool) && typeof args.command === "string" && WRITE_SHAPED.test(args.command)) {
    // Every token that looks like a path; quotes stripped.
    for (const tok of args.command.split(/\s+/)) {
      const clean = tok.replace(/^["']|["']$/g, "").replace(/^>+/, "");
      if (!clean || clean.startsWith("-")) continue;
      target = hit(clean);
      if (target) break;
    }
  }
  if (!target) return 0;

  process.stderr.write(
    `ZDD fence: ${target} is a generated artifact — never hand-edit it. ` +
      `Run the ZDD update ritual ("update ZDD" / the \`update\` skill) to regenerate it ` +
      `(zdd-engine derive + render). To lift the fence for this repo set "hooks": { "fence": false } in zdd/config.json.\n`,
  );
  return 2;
}

let code = 0;
try {
  code = main();
} catch {
  code = 0;
}
process.exit(code);
