// The agent index's area folder is ZDD's only where ZDD wrote it (CAS-103
// campaign 3, CR-501/503/504/505/526): render prunes an area file that
// carries the generated header and never touches anything else; at two
// levels the folder must be ZDD's alone; the folder cannot be the index
// file itself, cannot overlap a store, and ADR links climb to the
// configured adrDir. Run: node --test "test/*.test.mjs"
import { test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync, rmSync, mkdtempSync, cpSync, existsSync, readdirSync, mkdirSync, renameSync, symlinkSync } from "node:fs";
import { dirname, resolve, join } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import { agentIndexAreaDir } from "../src/render.mjs";

const PKG = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const BIN = join(PKG, "bin", "zdd-engine.mjs");
const FIXTURE = join(PKG, "test", "fixture");

const mkRepo = (t) => {
  const repo = mkdtempSync(join(tmpdir(), "zdd-own-"));
  t.after(() => rmSync(repo, { recursive: true, force: true }));
  cpSync(FIXTURE, repo, { recursive: true });
  return repo;
};
const run = (repo, args) => spawnSync(process.execPath, [BIN, ...args], { cwd: repo, encoding: "utf8" });
const config = (repo, patch) => {
  const p = join(repo, "zdd", "config.json");
  const cur = JSON.parse(readFileSync(p, "utf8"));
  writeFileSync(p, JSON.stringify({ ...cur, ...patch, agentIndex: { ...(cur.agentIndex ?? {}), ...(patch.agentIndex ?? {}) }, paths: { ...(cur.paths ?? {}), ...(patch.paths ?? {}) } }, null, 2));
};
const feature = (repo, name, tags, body = "") =>
  writeFileSync(join(repo, "zdd", "map", "features", `${name}.md`), `---\ntype: Feature\ntitle: ${name}\ndescription: ${name} feature\ntags: [${tags}]\n---\n\n${body}`);

test("CR-503: the area folder is the index's name without its extension; an index with no extension gets -areas, so the folder is never the file", () => {
  assert.equal(agentIndexAreaDir("zdd/agent-index.md"), "zdd/agent-index");
  assert.equal(agentIndexAreaDir("zdd/index.txt"), "zdd/index");
  assert.equal(agentIndexAreaDir("docs/agent-index"), "docs/agent-index-areas");
  assert.equal(agentIndexAreaDir("zdd/v2.1/index.md"), "zdd/v2.1/index");
});

test("CR-501: at one level an adopter's file under the index's folder is left alone by render and by --check; a stale generated area file is pruned; at two levels a foreign file makes render refuse, naming it", (t) => {
  const repo = mkRepo(t);
  const dir = join(repo, "zdd", "agent-index");
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "notes.md"), "# My notes\n\nMine.\n");
  writeFileSync(join(dir, "old-area.md"), "# Fixture App — old\n\nOne area of [the agent index](../agent-index.md). Generated by `zdd-engine render` — do not edit.\n");
  assert.equal(run(repo, ["derive"]).status, 0);
  const r = run(repo, ["render"]);
  assert.equal(r.status, 0, r.stderr);
  assert.equal(readFileSync(join(dir, "notes.md"), "utf8"), "# My notes\n\nMine.\n", "the adopter's file is untouched");
  assert.ok(!existsSync(join(dir, "old-area.md")), "ZDD's own stale area file is pruned");
  assert.equal(run(repo, ["render", "--check"]).status, 0, "a foreign file is not stale");
  // Two levels: the folder must be ZDD's alone.
  feature(repo, "billing", "billing");
  config(repo, { agentIndex: { levels: 2 } });
  assert.equal(run(repo, ["derive"]).status, 0);
  const refused = run(repo, ["render"]);
  assert.equal(refused.status, 1);
  assert.match(refused.stderr, /agent-index\/ holds a file that ZDD did not write \(notes\.md\) — agentIndex\.levels 2 writes one file per area there and prunes the folder/, refused.stderr);
  assert.equal(readFileSync(join(dir, "notes.md"), "utf8"), "# My notes\n\nMine.\n");
  const check = run(repo, ["render", "--check"]);
  assert.equal(check.status, 1);
  assert.match(check.stderr, /holds a file that ZDD did not write/);
  rmSync(join(dir, "notes.md"));
  assert.equal(run(repo, ["render"]).status, 0);
  assert.deepEqual(readdirSync(dir).sort(), ["billing.md", "things.md"]);
});

test("CR-501: the area folder may not overlap a store or another output — the layout check names the index and the folder", (t) => {
  const repo = mkRepo(t);
  config(repo, { paths: { agentIndex: "zdd/map.md" } });
  const r = run(repo, ["render"]);
  assert.equal(r.status, 1);
  assert.match(r.stderr, /paths\.agentIndex 'zdd\/map\.md' overlaps paths\.mapDir 'zdd\/map' — the agent index's area folder 'zdd\/map\/'/, r.stderr);
  config(repo, { paths: { agentIndex: "zdd/adr.md" } });
  assert.match(run(repo, ["derive"]).stderr, /paths\.agentIndex 'zdd\/adr\.md' overlaps paths\.adrDir 'zdd\/adr'/);
});

test("CR-503/CR-526: a file or a symlink where the area folder would be is refused before anything is made; an extensionless index renders with its -areas folder", (t) => {
  const repo = mkRepo(t);
  assert.equal(run(repo, ["derive"]).status, 0);
  writeFileSync(join(repo, "zdd", "agent-index"), "not a folder\n");
  const r = run(repo, ["render"]);
  assert.equal(r.status, 1);
  assert.match(r.stderr, /agent-index\/ \(.*\) is not a folder/, r.stderr);
  rmSync(join(repo, "zdd", "agent-index"));
  const outside = mkdtempSync(join(tmpdir(), "zdd-outside-"));
  t.after(() => rmSync(outside, { recursive: true, force: true }));
  let linked = true;
  try {
    symlinkSync(outside, join(repo, "zdd", "agent-index"), "junction");
  } catch {
    linked = false;
  }
  if (linked) {
    feature(repo, "billing", "billing");
    config(repo, { agentIndex: { levels: 2 } });
    assert.equal(run(repo, ["derive"]).status, 0);
    const s = run(repo, ["render"]);
    assert.equal(s.status, 1);
    assert.match(s.stderr, /is a symlink — the agent index's area folder must be a real folder inside the repo/, s.stderr);
    assert.deepEqual(readdirSync(outside), [], "nothing was written through the link");
    rmSync(join(repo, "zdd", "agent-index"), { recursive: true, force: true });
    config(repo, { agentIndex: { levels: 1 } });
  }
  config(repo, { paths: { agentIndex: "zdd/agent-index" }, agentIndex: { levels: 2 } });
  feature(repo, "billing", "billing");
  assert.equal(run(repo, ["derive"]).status, 0);
  const ok = run(repo, ["render"]);
  assert.equal(ok.status, 0, ok.stderr);
  assert.ok(existsSync(join(repo, "zdd", "agent-index-areas", "billing.md")));
  assert.match(readFileSync(join(repo, "zdd", "agent-index"), "utf8"), /\(agent-index-areas\/billing\.md\)/);
  assert.match(ok.stdout, /feature sections -> 2 area files under agent-index-areas\//, ok.stdout);
});

test("CR-504: two areas that fold to one file name are refused naming both; area names are lower-case letters, digits and dashes", (t) => {
  const repo = mkRepo(t);
  feature(repo, "a", "Foo Bar");
  feature(repo, "b", "foo-bar");
  config(repo, { agentIndex: { levels: 2 } });
  assert.equal(run(repo, ["derive"]).status, 0);
  const r = run(repo, ["render"]);
  assert.equal(r.status, 1);
  assert.match(r.stderr, /the areas 'Foo Bar' and 'foo-bar' would both be written as agent-index\/foo-bar\.md — rename one tag/, r.stderr);
  rmSync(join(repo, "zdd", "map", "features", "b.md"));
  feature(repo, "c", "Ops EU/West");
  assert.equal(run(repo, ["derive"]).status, 0);
  const ok = run(repo, ["render"]);
  assert.equal(ok.status, 0, ok.stderr);
  assert.ok(existsSync(join(repo, "zdd", "agent-index", "ops-eu-west.md")), readdirSync(join(repo, "zdd", "agent-index")).join());
  assert.match(readFileSync(join(repo, "zdd", "agent-index.md"), "utf8"), /^- \[Ops EU\/West\]\(agent-index\/ops-eu-west\.md\)/m);
});

test("CR-505: an area file's ADR links climb to paths.adrDir wherever it is", (t) => {
  const repo = mkRepo(t);
  mkdirSync(join(repo, "docs"), { recursive: true });
  renameSync(join(repo, "zdd", "adr"), join(repo, "docs", "decisions"));
  config(repo, { paths: { adrDir: "docs/decisions" }, agentIndex: { levels: 2 } });
  writeFileSync(join(repo, "zdd", "map", "features", "billing.md"), "---\ntype: Feature\ntitle: billing\ndescription: Billing, per ADR-0002.\ntags: [billing]\n---\n");
  assert.equal(run(repo, ["derive"]).status, 0);
  const r = run(repo, ["render"]);
  assert.equal(r.status, 0, r.stderr);
  const area = readFileSync(join(repo, "zdd", "agent-index", "billing.md"), "utf8");
  assert.match(area, /\[ADR-0002\]\(\.\.\/\.\.\/docs\/decisions\/0002-things-replace-widgets\.md\)/, area);
});
