// Composed extractors (DIO-309): config `extractors: [...]` replaces the single
// `adapter`; the deriver runs each extractor, merges records and resolves refs
// after the merge. Exercised through the real CLI against throwaway fixture
// copies. The golden under test/golden/ was generated by v0.3.1's monolithic
// `nextjs-supabase` adapter — byte-identity with it is the split's contract.
// Run: node --test "test/*.test.mjs"
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import { readFileSync, writeFileSync, rmSync, mkdtempSync, cpSync, existsSync, readdirSync, statSync, mkdirSync } from "node:fs";
import { dirname, resolve, join, relative } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";

const PKG = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const BIN = join(PKG, "bin", "zdd-engine.mjs");
const FIXTURE = join(PKG, "test", "fixture");
const FIXTURE_FASTAPI = join(PKG, "test", "fixture-fastapi");
const FIXTURE_GREENFIELD = join(PKG, "test", "fixture-greenfield");
const GOLDEN = join(PKG, "test", "golden", "nextjs-supabase-metadata");

const mkRepo = (fixture) => {
  const repo = mkdtempSync(join(tmpdir(), "zdd-ext-"));
  cpSync(fixture, repo, { recursive: true });
  return repo;
};
const run = (repo, args) =>
  execFileSync(process.execPath, [BIN, ...args], { cwd: repo, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
const runFail = (repo, args) => {
  try {
    run(repo, args);
  } catch (err) {
    return String(err.stderr);
  }
  assert.fail(`expected non-zero exit for ${args.join(" ")}`);
};
const readConfig = (repo) => JSON.parse(readFileSync(join(repo, "zdd", "config.json"), "utf8"));
const writeConfig = (repo, config) => writeFileSync(join(repo, "zdd", "config.json"), JSON.stringify(config, null, 2));
const tree = (dir, base = dir, out = new Map()) => {
  if (!existsSync(dir)) return out;
  for (const name of readdirSync(dir).sort()) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) tree(p, base, out);
    else out.set(relative(base, p).split(/[\\/]/).join("/"), readFileSync(p, "utf8"));
  }
  return out;
};
const assertTreesEqual = (a, b, label) => {
  assert.deepEqual([...a.keys()], [...b.keys()], `${label}: file sets differ`);
  for (const [rel, content] of a) assert.equal(content, b.get(rel), `${label}: ${rel} differs`);
};
// The v0.3.1 fixture config expressed as composed extractors.
const composedConfig = (legacy) => {
  const { adapter, adapterOptions, ...rest } = legacy;
  const { migrationNamespaces, externalBuckets, ...nextjs } = adapterOptions;
  return { ...rest, extractors: ["supabase", "nextjs"], extractorOptions: { supabase: { migrationNamespaces, externalBuckets }, nextjs } };
};

test("extractors [supabase, nextjs] reproduce the v0.3.1 adapter output byte-for-byte", () => {
  const repo = mkRepo(FIXTURE);
  writeConfig(repo, composedConfig(readConfig(repo)));
  run(repo, ["derive"]);
  assertTreesEqual(tree(join(repo, "zdd", "metadata")), tree(GOLDEN), "composed vs golden");
  rmSync(repo, { recursive: true, force: true });
});

test("legacy adapter key still works: golden output + one deprecation line", () => {
  const repo = mkRepo(FIXTURE);
  const { status, stdout, stderr } = spawnSync(process.execPath, [BIN, "derive"], { cwd: repo, encoding: "utf8" });
  assert.equal(status, 0, stderr);
  assert.match(stdout, /Wrote 15 records/);
  assertTreesEqual(tree(join(repo, "zdd", "metadata")), tree(GOLDEN), "legacy vs golden");
  // Deprecation note is printed on stderr, without --verbose, exactly once.
  const lines = stderr.split("\n").filter((l) => /deprecated/.test(l));
  assert.equal(lines.length, 1, stderr);
  assert.match(lines[0], /'adapter'.*extractors/);
  rmSync(repo, { recursive: true, force: true });
});

test("fastapi + supabase: prefix-aware router routes, app routes, tables from migrations, table refs", () => {
  const repo = mkRepo(FIXTURE_FASTAPI);
  assert.match(run(repo, ["derive"]), /Wrote 4 records/);
  const meta = join(repo, "zdd", "metadata");
  const jobRoute = JSON.parse(readFileSync(join(meta, "route", "jobs--_id.json"), "utf8"));
  assert.equal(jobRoute.id, "route:/jobs/{id}");
  assert.deepEqual(jobRoute.facts.methods, ["GET", "DELETE"]);
  assert.deepEqual(jobRoute.facts.dynamicSegments, ["id"]);
  assert.deepEqual(jobRoute.resource, ["api/routes/jobs.py"]);
  assert.equal(jobRoute.description, "Fetch one job by id.");
  assert.deepEqual(jobRoute.refs, ["table:db/jobs"]);
  const offers = JSON.parse(readFileSync(join(meta, "route", "offers.json"), "utf8"));
  assert.equal(offers.id, "route:/offers");
  assert.deepEqual(offers.facts.methods, ["POST"]);
  assert.deepEqual(offers.resource, ["main.py"]);
  assert.deepEqual(offers.refs, ["table:db/offers"]);
  assert.ok(existsSync(join(meta, "table", "db--jobs.json")));
  const offersTable = JSON.parse(readFileSync(join(meta, "table", "db--offers.json"), "utf8"));
  assert.deepEqual(offersTable.refs, ["table:db/jobs"]);
  assert.match(run(repo, ["derive", "--check"]), /in sync/);
  rmSync(repo, { recursive: true, force: true });
});

test("greenfield: config only, no source dirs — derive/render and both --checks exit 0, metadata empty", () => {
  const repo = mkRepo(FIXTURE_GREENFIELD);
  assert.match(run(repo, ["derive"]), /0 records/);
  assert.match(run(repo, ["derive", "--check"]), /in sync \(0 records\)/);
  run(repo, ["render"]);
  assert.match(run(repo, ["render", "--check"]), /in sync/);
  assert.equal(tree(join(repo, "zdd", "metadata")).size, 0);
  assert.match(readFileSync(join(repo, "zdd", "agent-index.md"), "utf8"), /^# Greenfield/m);
  rmSync(repo, { recursive: true, force: true });
});

test("generic: emits nothing; render still produces the agent index from the map alone", () => {
  const repo = mkRepo(FIXTURE);
  const config = readConfig(repo);
  delete config.adapter;
  delete config.adapterOptions;
  writeConfig(repo, { ...config, extractors: ["generic"] });
  assert.match(run(repo, ["derive"]), /0 records/);
  assert.equal(tree(join(repo, "zdd", "metadata")).size, 0);
  // The fixture map links into metadata that no longer exists — a map-only
  // bundle's map is link-free, so give it one.
  writeFileSync(
    join(repo, "zdd", "map", "features", "things.md"),
    "---\ntype: Feature\ntitle: Things\ndescription: CRUD for things (ADR-0002).\nresource: src/components\ntags: [things]\n---\n\nThe things catalogue.\n",
  );
  run(repo, ["render"]);
  const index = readFileSync(join(repo, "zdd", "agent-index.md"), "utf8");
  assert.match(index, /^## Things/m);
  assert.match(run(repo, ["render", "--check"]), /in sync/);
  rmSync(repo, { recursive: true, force: true });
});

const DEMO_EXTRACTOR = `export const FACTS_KEY_ORDER = { job: ["schedule"] };
export function derive({ repoRoot, options }) {
  return {
    records: [{ kind: "job", id: "job:nightly", title: "nightly", description: "Demo job.", resource: [], refs: [], facts: { schedule: options.schedule ?? "daily" }, filename: "nightly.json" }],
    diagnostics: [],
  };
}
`;

test("localExtractorDir: a repo-local extractor is selected by name; a path string is refused", () => {
  const repo = mkRepo(FIXTURE_GREENFIELD);
  mkdirSync(join(repo, "zdd", "extractors"), { recursive: true });
  writeFileSync(join(repo, "zdd", "extractors", "demo.mjs"), DEMO_EXTRACTOR);
  const base = readConfig(repo);
  writeConfig(repo, { ...base, localExtractorDir: "zdd/extractors", extractors: ["demo"], extractorOptions: { demo: { schedule: "nightly" } } });
  assert.match(run(repo, ["derive"]), /Wrote 1 records/);
  const job = JSON.parse(readFileSync(join(repo, "zdd", "metadata", "job", "nightly.json"), "utf8"));
  assert.equal(job.id, "job:nightly");
  assert.equal(job.facts.schedule, "nightly");

  writeConfig(repo, { ...base, localExtractorDir: "zdd/extractors", extractors: ["zdd/extractors/demo.mjs"] });
  const err = runFail(repo, ["derive"]);
  assert.match(err, /by name, never by path/);
  assert.match(err, /localExtractorDir/);
  rmSync(repo, { recursive: true, force: true });
});

test("unknown extractor name lists the known names: registry + local dir", () => {
  const repo = mkRepo(FIXTURE_GREENFIELD);
  mkdirSync(join(repo, "zdd", "extractors"), { recursive: true });
  writeFileSync(join(repo, "zdd", "extractors", "demo.mjs"), DEMO_EXTRACTOR);
  writeConfig(repo, { ...readConfig(repo), localExtractorDir: "zdd/extractors", extractors: ["rails"] });
  const err = runFail(repo, ["derive"]);
  assert.match(err, /Unknown extractor 'rails'/);
  for (const name of ["supabase", "nextjs", "fastapi", "generic", "demo"]) assert.ok(err.includes(name), `${name} listed: ${err}`);
  rmSync(repo, { recursive: true, force: true });
});

test("determinism: derive + render twice on every fixture is byte-identical across zdd/", () => {
  const cases = [
    ["nextjs-supabase composed", FIXTURE, (r) => writeConfig(r, composedConfig(readConfig(r)))],
    ["fastapi", FIXTURE_FASTAPI, () => {}],
    ["greenfield", FIXTURE_GREENFIELD, () => {}],
  ];
  for (const [label, fixture, prep] of cases) {
    const a = mkRepo(fixture);
    const b = mkRepo(fixture);
    prep(a);
    prep(b);
    for (const r of [a, b]) {
      run(r, ["derive"]);
      run(r, ["render"]);
    }
    assertTreesEqual(tree(join(a, "zdd")), tree(join(b, "zdd")), label);
    rmSync(a, { recursive: true, force: true });
    rmSync(b, { recursive: true, force: true });
  }
});

test("config.schema.json describes extractors + localExtractorDir and deprecates adapter", () => {
  const schema = JSON.parse(readFileSync(join(PKG, "..", "..", "plugins", "zdd", "templates", "config.schema.json"), "utf8"));
  assert.equal(schema.properties.extractors.type, "array");
  assert.ok(schema.properties.extractors.description);
  assert.equal(schema.properties.localExtractorDir.type, "string");
  assert.ok(schema.properties.localExtractorDir.description);
  assert.equal(schema.properties.extractorOptions.type, "object");
  assert.equal(schema.properties.adapter.deprecated, true);
  assert.equal(schema.properties.adapterOptions.deprecated, true);
  assert.ok(!schema.required?.includes("adapter"), "adapter is no longer required");
});
