// Composed extractors (DIO-309): config `extractors: [...]` replaces the single
// `adapter`; the deriver runs each extractor, merges records and resolves refs
// after the merge. Exercised through the real CLI against throwaway fixture
// copies. The golden under test/golden/ was generated by v0.3.1's monolithic
// `nextjs-supabase` adapter — byte-identity with it is the split's contract.
// Run: node --test "test/*.test.mjs"
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import { readFileSync, writeFileSync, rmSync, mkdtempSync, cpSync, existsSync, readdirSync, statSync, mkdirSync } from "node:fs";
import { dirname, resolve, join, relative } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";

const PKG = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const BIN = join(PKG, "bin", "zdd-engine.mjs");
const FIXTURE = join(PKG, "test", "fixture");
const FIXTURE_FASTAPI = join(PKG, "test", "fixture-fastapi");
const FIXTURE_GREENFIELD = join(PKG, "test", "fixture-greenfield");
const GOLDEN = join(PKG, "test", "golden", "nextjs-supabase-metadata");

const mkRepo = (fixture) => {
  const repo = mkdtempSync(join(tmpdir(), "zdd-ext-"));
  cpSync(fixture, repo, { recursive: true });
  return repo;
};
const run = (repo, args) =>
  execFileSync(process.execPath, [BIN, ...args], { cwd: repo, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
const runFail = (repo, args) => {
  try {
    run(repo, args);
  } catch (err) {
    return String(err.stderr);
  }
  assert.fail(`expected non-zero exit for ${args.join(" ")}`);
};
const readConfig = (repo) => JSON.parse(readFileSync(join(repo, "zdd", "config.json"), "utf8"));
const writeConfig = (repo, config) => writeFileSync(join(repo, "zdd", "config.json"), JSON.stringify(config, null, 2));
const tree = (dir, base = dir, out = new Map()) => {
  if (!existsSync(dir)) return out;
  for (const name of readdirSync(dir).sort()) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) tree(p, base, out);
    else out.set(relative(base, p).split(/[\\/]/).join("/"), readFileSync(p, "utf8"));
  }
  return out;
};
const assertTreesEqual = (a, b, label) => {
  assert.deepEqual([...a.keys()], [...b.keys()], `${label}: file sets differ`);
  for (const [rel, content] of a) assert.equal(content, b.get(rel), `${label}: ${rel} differs`);
};
// The v0.3.1 fixture config expressed as composed extractors.
const composedConfig = (legacy) => {
  const { adapter, adapterOptions, ...rest } = legacy;
  const { migrationNamespaces, externalBuckets, ...nextjs } = adapterOptions;
  return { ...rest, extractors: ["supabase", "nextjs"], extractorOptions: { supabase: { migrationNamespaces, externalBuckets }, nextjs } };
};

test("extractors [supabase, nextjs] reproduce the v0.3.1 adapter output byte-for-byte", () => {
  const repo = mkRepo(FIXTURE);
  writeConfig(repo, composedConfig(readConfig(repo)));
  run(repo, ["derive"]);
  assertTreesEqual(tree(join(repo, "zdd", "metadata")), tree(GOLDEN), "composed vs golden");
  rmSync(repo, { recursive: true, force: true });
});

test("legacy adapter key still works: golden output + one deprecation line", () => {
  const repo = mkRepo(FIXTURE);
  const { status, stdout, stderr } = spawnSync(process.execPath, [BIN, "derive"], { cwd: repo, encoding: "utf8" });
  assert.equal(status, 0, stderr);
  assert.match(stdout, /Wrote 15 records/);
  assertTreesEqual(tree(join(repo, "zdd", "metadata")), tree(GOLDEN), "legacy vs golden");
  // Deprecation note is printed on stderr, without --verbose, exactly once.
  const lines = stderr.split("\n").filter((l) => /deprecated/.test(l));
  assert.equal(lines.length, 1, stderr);
  assert.match(lines[0], /'adapter'.*extractors/);
  rmSync(repo, { recursive: true, force: true });
});

test("fastapi + supabase: prefix-aware router routes, app routes, tables from migrations, table refs", () => {
  const repo = mkRepo(FIXTURE_FASTAPI);
  assert.match(run(repo, ["derive"]), /Wrote 4 records/);
  const meta = join(repo, "zdd", "metadata");
  const jobRoute = JSON.parse(readFileSync(join(meta, "route", "jobs--_id.json"), "utf8"));
  assert.equal(jobRoute.id, "route:/jobs/{id}");
  assert.deepEqual(jobRoute.facts.methods, ["GET", "DELETE"]);
  assert.deepEqual(jobRoute.facts.dynamicSegments, ["id"]);
  assert.deepEqual(jobRoute.resource, ["api/routes/jobs.py"]);
  assert.equal(jobRoute.description, "Fetch one job by id.");
  assert.deepEqual(jobRoute.refs, ["table:db/jobs"]);
  const offers = JSON.parse(readFileSync(join(meta, "route", "offers.json"), "utf8"));
  assert.equal(offers.id, "route:/offers");
  assert.deepEqual(offers.facts.methods, ["POST"]);
  assert.deepEqual(offers.resource, ["main.py"]);
  assert.deepEqual(offers.refs, ["table:db/offers"]);
  assert.ok(existsSync(join(meta, "table", "db--jobs.json")));
  const offersTable = JSON.parse(readFileSync(join(meta, "table", "db--offers.json"), "utf8"));
  assert.deepEqual(offersTable.refs, ["table:db/jobs"]);
  assert.match(run(repo, ["derive", "--check"]), /in sync/);
  rmSync(repo, { recursive: true, force: true });
});

test("CR-097: fastapi + supabase fixture equals its committed goldens (metadata tree, graph.json, agent-index.md)", () => {
  // Goldens under test/golden/fastapi-supabase-*; regenerate only as a
  // deliberate, narrated step (command in test/golden/README.md).
  const repo = mkRepo(FIXTURE_FASTAPI);
  run(repo, ["derive"]);
  run(repo, ["render"]);
  assertTreesEqual(tree(join(repo, "zdd", "metadata")), tree(join(PKG, "test", "golden", "fastapi-supabase-metadata")), "fastapi metadata vs golden");
  assert.equal(readFileSync(join(repo, "zdd", "graph.json"), "utf8"), readFileSync(join(PKG, "test", "golden", "fastapi-supabase-graph.json"), "utf8"));
  const agentIndex = readFileSync(join(repo, "zdd", "agent-index.md"), "utf8");
  assert.equal(agentIndex, readFileSync(join(PKG, "test", "golden", "fastapi-supabase-agent-index.md"), "utf8"));
  // CR-118: this fixture has no agentIndex.summary. The renderer used to emit
  // `> ` (trailing space) for it, which fails `git diff --check` in every
  // adopter's CI; now the empty blockquote is omitted altogether.
  assert.ok(!/[ \t]+$/m.test(agentIndex), "agent-index.md has no trailing whitespace on any line");
  assert.ok(!/^>\s*$/m.test(agentIndex), "no empty blockquote line");
  assert.match(agentIndex, /^# Fixture FastAPI\n\nGenerated by /, "title runs straight into the generated-by line");
  rmSync(repo, { recursive: true, force: true });
});

test("greenfield: config only, no source dirs — derive/render/lint and both --checks exit 0, metadata empty, roots reported", () => {
  const repo = mkRepo(FIXTURE_GREENFIELD);
  const { status, stdout, stderr } = spawnSync(process.execPath, [BIN, "derive", "--verbose"], { cwd: repo, encoding: "utf8" });
  assert.equal(status, 0, stderr);
  assert.match(stdout, /0 records/);
  // Missing roots are "nothing to inventory" — but always said (CR-002).
  assert.match(stderr, /\[supabase\] db: supabase\/migrations not found — nothing to inventory/);
  assert.match(stderr, /\[fastapi\] api not found — nothing to inventory/);
  assert.match(run(repo, ["derive", "--check"]), /in sync \(0 records\)/);
  run(repo, ["render"]);
  assert.match(run(repo, ["render", "--check"]), /in sync/);
  assert.match(run(repo, ["lint"]), /store lints passed/); // --tempstate needs git; fixture copies have none
  assert.equal(tree(join(repo, "zdd", "metadata")).size, 0);
  assert.match(readFileSync(join(repo, "zdd", "agent-index.md"), "utf8"), /^# Greenfield/m);
  rmSync(repo, { recursive: true, force: true });
});

test("config guards through the CLI: empty list, mixed legacy+new, escaping paths all fail before touching metadata (CR-001/004/005/006/019)", () => {
  const repo = mkRepo(FIXTURE);
  run(repo, ["derive"]);
  const before = tree(join(repo, "zdd", "metadata"));
  const legacy = readConfig(repo);
  const cases = [
    [{ ...composedConfig(legacy), extractors: [] }, /lists nothing/],
    [{ ...legacy, extractors: ["supabase", "nextjs"] }, /both 'adapter' and 'extractors'/],
    [{ ...composedConfig(legacy), localExtractorDir: "../elsewhere" }, /localExtractorDir '\.\.\/elsewhere' must be repo-relative/],
    [{ ...composedConfig(legacy), paths: { humanIndex: "../package.json" } }, /paths\.humanIndex .* must be repo-relative/],
    [(() => { const c = composedConfig(legacy); c.extractorOptions.supabase.migrationNamespaces = [{ name: "db", dir: "../fixture/migrations" }]; return c; })(), /supabase\.migrationNamespaces\[db\]\.dir .* must be repo-relative/],
    [(() => { const c = composedConfig(legacy); c.extractorOptions.nextjs.appDir = "/etc"; return c; })(), /nextjs\.appDir .* must be repo-relative/],
  ];
  for (const [config, re] of cases) {
    writeConfig(repo, config);
    assert.match(runFail(repo, ["derive"]), re);
    assertTreesEqual(tree(join(repo, "zdd", "metadata")), before, "metadata untouched after refused config");
  }
  rmSync(repo, { recursive: true, force: true });
});

test("record guards: a local extractor cannot write outside metadataDir via kind, nor name a '..' resource (CR-003/005)", () => {
  const repo = mkRepo(FIXTURE_GREENFIELD);
  mkdirSync(join(repo, "zdd", "extractors"), { recursive: true });
  const base = { ...readConfig(repo), localExtractorDir: "zdd/extractors", extractors: ["evil"] };
  writeConfig(repo, base);
  const evil = (record) => `export function derive() { return { records: [${record}], diagnostics: [] }; }`;
  writeFileSync(join(repo, "zdd", "extractors", "evil.mjs"), evil(`{ kind: "..", id: "x:1", title: "x", description: "", resource: [], refs: [], facts: {}, filename: "config.json" }`));
  assert.match(runFail(repo, ["derive"]), /bad kind '\.\.'/);
  assert.match(readFileSync(join(repo, "zdd", "config.json"), "utf8"), /Greenfield/, "config.json not overwritten");
  writeFileSync(join(repo, "zdd", "extractors", "evil.mjs"), evil(`{ kind: "job", id: "job:1", title: "x", description: "", resource: ["../secret.sql"], refs: [], facts: {}, filename: "x.json" }`));
  assert.match(runFail(repo, ["derive"]), /resource '\.\.\/secret\.sql' must be repo-relative/);
  rmSync(repo, { recursive: true, force: true });
});

test("CR-093: a record carrying undefined / a function / a symbol fails derive naming the record — never `undefined` written into a .json", () => {
  const repo = mkRepo(FIXTURE_GREENFIELD);
  mkdirSync(join(repo, "zdd", "extractors"), { recursive: true });
  writeConfig(repo, { ...readConfig(repo), localExtractorDir: "zdd/extractors", extractors: ["sloppy"] });
  const sloppy = (facts) => `export function derive() { return { records: [{ kind: "job", id: "job:1", title: "x", description: "", resource: [], refs: [], facts: ${facts}, filename: "x.json" }], diagnostics: [] }; }`;
  for (const [facts, where] of [
    ["{ auth: undefined }", /facts\.auth/],
    ["{ nested: { deep: [1, undefined] } }", /facts\.nested\.deep\[1\]/],
    ["{ fn: () => 1 }", /facts\.fn/],
    ["{ sym: Symbol('s') }", /facts\.sym/],
  ]) {
    writeFileSync(join(repo, "zdd", "extractors", "sloppy.mjs"), sloppy(facts));
    const err = runFail(repo, ["derive"]);
    assert.match(err, /Record job:1: .*not serialisable/, facts);
    assert.match(err, where, facts);
    assert.ok(!existsSync(join(repo, "zdd", "metadata", "job", "x.json")), `nothing written for ${facts}`);
  }
  rmSync(repo, { recursive: true, force: true });
});

test("two extractors emitting one kind: facts orders merge in config order; duplicate ids and case-variant filenames fail (CR-023)", () => {
  const repo = mkRepo(FIXTURE_GREENFIELD);
  mkdirSync(join(repo, "zdd", "extractors"), { recursive: true });
  const ext = (id, filename, facts, order) =>
    `export const FACTS_KEY_ORDER = { job: ${JSON.stringify(order)} };\nexport function derive() { return { records: [{ kind: "job", id: ${JSON.stringify(id)}, title: "t", description: "", resource: [], refs: [], facts: ${JSON.stringify(facts)}, filename: ${JSON.stringify(filename)} }], diagnostics: [] }; }`;
  writeFileSync(join(repo, "zdd", "extractors", "one.mjs"), ext("job:a", "a.json", { zeta: 1, alpha: 2 }, ["zeta"]));
  writeFileSync(join(repo, "zdd", "extractors", "two.mjs"), ext("job:b", "b.json", { alpha: 1, zeta: 2, beta: 3 }, ["alpha", "beta"]));
  const base = { ...readConfig(repo), localExtractorDir: "zdd/extractors" };
  writeConfig(repo, { ...base, extractors: ["one", "two"] });
  assert.match(run(repo, ["derive"]), /Wrote 2 records/);
  // Merged order is zeta, alpha, beta for both records regardless of emitter.
  assert.deepEqual(Object.keys(JSON.parse(readFileSync(join(repo, "zdd", "metadata", "job", "b.json"), "utf8")).facts), ["zeta", "alpha", "beta"]);
  writeFileSync(join(repo, "zdd", "extractors", "two.mjs"), ext("job:a", "b.json", {}, []));
  assert.match(runFail(repo, ["derive"]), /Duplicate record id 'job:a'/);
  writeFileSync(join(repo, "zdd", "extractors", "two.mjs"), ext("job:b", "A.json", {}, []));
  assert.match(runFail(repo, ["derive"]), /Filename collision \(case-insensitive\): job\/a\.json/);
  rmSync(repo, { recursive: true, force: true });
});

test("a local extractor named like an Object.prototype property loads from the local dir (CR-022)", () => {
  const repo = mkRepo(FIXTURE_GREENFIELD);
  mkdirSync(join(repo, "zdd", "extractors"), { recursive: true });
  writeFileSync(join(repo, "zdd", "extractors", "constructor.mjs"), DEMO_EXTRACTOR);
  writeConfig(repo, { ...readConfig(repo), localExtractorDir: "zdd/extractors", extractors: ["constructor"] });
  assert.match(run(repo, ["derive"]), /Wrote 1 records/);
  rmSync(repo, { recursive: true, force: true });
});

test("render tolerates a third-party route record with foreign facts (CR-014)", () => {
  const repo = mkRepo(FIXTURE_GREENFIELD);
  mkdirSync(join(repo, "zdd", "extractors"), { recursive: true });
  writeFileSync(
    join(repo, "zdd", "extractors", "rails.mjs"),
    `export function derive() { return { records: [{ kind: "route", id: "route:/posts", title: "/posts", description: "", resource: ["config/routes.rb"], refs: [], facts: { controller: "posts#index" }, filename: "posts.json" }], diagnostics: [] }; }`,
  );
  writeConfig(repo, { ...readConfig(repo), localExtractorDir: "zdd/extractors", extractors: ["rails"] });
  run(repo, ["derive"]);
  run(repo, ["render"]);
  const html = readFileSync(join(repo, "zdd", "human-index.html"), "utf8");
  assert.ok(!html.includes("# Auth\\n\\nundefined"), "no undefined auth section");
  rmSync(repo, { recursive: true, force: true });
});

test("generic: emits nothing; render still produces the agent index from the map alone", () => {
  const repo = mkRepo(FIXTURE);
  const config = readConfig(repo);
  delete config.adapter;
  delete config.adapterOptions;
  writeConfig(repo, { ...config, extractors: ["generic"] });
  assert.match(run(repo, ["derive"]), /0 records/);
  assert.equal(tree(join(repo, "zdd", "metadata")).size, 0);
  // The fixture map links into metadata that no longer exists — a map-only
  // bundle's map is link-free, so give it one.
  writeFileSync(
    join(repo, "zdd", "map", "features", "things.md"),
    "---\ntype: Feature\ntitle: Things\ndescription: CRUD for things (ADR-0002).\nresource: src/components\ntags: [things]\n---\n\nThe things catalogue.\n",
  );
  run(repo, ["render"]);
  const index = readFileSync(join(repo, "zdd", "agent-index.md"), "utf8");
  assert.match(index, /^## Things/m);
  assert.match(run(repo, ["render", "--check"]), /in sync/);
  rmSync(repo, { recursive: true, force: true });
});

const DEMO_EXTRACTOR = `export const FACTS_KEY_ORDER = { job: ["schedule"] };
export function derive({ repoRoot, options }) {
  return {
    records: [{ kind: "job", id: "job:nightly", title: "nightly", description: "Demo job.", resource: [], refs: [], facts: { schedule: options.schedule ?? "daily" }, filename: "nightly.json" }],
    diagnostics: [],
  };
}
`;

test("localExtractorDir: a repo-local extractor is selected by name; a path string is refused", () => {
  const repo = mkRepo(FIXTURE_GREENFIELD);
  mkdirSync(join(repo, "zdd", "extractors"), { recursive: true });
  writeFileSync(join(repo, "zdd", "extractors", "demo.mjs"), DEMO_EXTRACTOR);
  const base = readConfig(repo);
  writeConfig(repo, { ...base, localExtractorDir: "zdd/extractors", extractors: ["demo"], extractorOptions: { demo: { schedule: "nightly" } } });
  assert.match(run(repo, ["derive"]), /Wrote 1 records/);
  const job = JSON.parse(readFileSync(join(repo, "zdd", "metadata", "job", "nightly.json"), "utf8"));
  assert.equal(job.id, "job:nightly");
  assert.equal(job.facts.schedule, "nightly");

  writeConfig(repo, { ...base, localExtractorDir: "zdd/extractors", extractors: ["zdd/extractors/demo.mjs"] });
  const err = runFail(repo, ["derive"]);
  assert.match(err, /by name, never by path/);
  assert.match(err, /localExtractorDir/);
  rmSync(repo, { recursive: true, force: true });
});

test("unknown extractor name lists the known names: registry + local dir", () => {
  const repo = mkRepo(FIXTURE_GREENFIELD);
  mkdirSync(join(repo, "zdd", "extractors"), { recursive: true });
  writeFileSync(join(repo, "zdd", "extractors", "demo.mjs"), DEMO_EXTRACTOR);
  writeConfig(repo, { ...readConfig(repo), localExtractorDir: "zdd/extractors", extractors: ["rails"] });
  const err = runFail(repo, ["derive"]);
  assert.match(err, /Unknown extractor 'rails'/);
  for (const name of ["supabase", "nextjs", "fastapi", "generic", "demo"]) assert.ok(err.includes(name), `${name} listed: ${err}`);
  rmSync(repo, { recursive: true, force: true });
});

test("determinism: derive + render on two fresh copies of every fixture, and twice on one copy, is byte-identical across zdd/", () => {
  const cases = [
    ["nextjs-supabase composed", FIXTURE, (r) => writeConfig(r, composedConfig(readConfig(r)))],
    ["fastapi", FIXTURE_FASTAPI, () => {}],
    ["greenfield", FIXTURE_GREENFIELD, () => {}],
  ];
  for (const [label, fixture, prep] of cases) {
    const a = mkRepo(fixture);
    const b = mkRepo(fixture);
    prep(a);
    prep(b);
    for (const r of [a, b]) {
      run(r, ["derive"]);
      run(r, ["render"]);
    }
    assertTreesEqual(tree(join(a, "zdd")), tree(join(b, "zdd")), label);
    const once = tree(join(a, "zdd"));
    run(a, ["derive"]);
    run(a, ["render"]);
    assertTreesEqual(tree(join(a, "zdd")), once, `${label} (idempotent)`);
    rmSync(a, { recursive: true, force: true });
    rmSync(b, { recursive: true, force: true });
  }
});

test("config.schema.json describes extractors + localExtractorDir and deprecates adapter", () => {
  const schema = JSON.parse(readFileSync(join(PKG, "..", "..", "plugins", "zdd", "templates", "config.schema.json"), "utf8"));
  assert.equal(schema.properties.extractors.type, "array");
  assert.ok(schema.properties.extractors.description);
  assert.equal(schema.properties.localExtractorDir.type, "string");
  assert.ok(schema.properties.localExtractorDir.description);
  assert.equal(schema.properties.extractorOptions.type, "object");
  assert.equal(schema.properties.adapter.deprecated, true);
  assert.equal(schema.properties.adapterOptions.deprecated, true);
  assert.ok(!schema.required?.includes("adapter"), "adapter is no longer required");
});
